# Generated by Django 5.2.6 on 2025-10-22 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='timeISO',
            field=models.DateTimeField(),
        ),
    ]
